/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 2.0.1.281.2
    Soft IP Version: 1.0.0
    Wed Apr 01 14:20:56 2020
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module fifo_dc_32_gen (wr_clk_i, rd_clk_i, rst_i, rp_rst_i, wr_en_i, rd_en_i,
    wr_data_i, full_o, empty_o, almost_empty_o, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  wr_clk_i;
    input  rd_clk_i;
    input  rst_i;
    input  rp_rst_i;
    input  wr_en_i;
    input  rd_en_i;
    input  [31:0]  wr_data_i;
    output  full_o;
    output  empty_o;
    output  almost_empty_o;
    output  [31:0]  rd_data_o;
endmodule