// File: bin2gray.v
// Generated by MyHDL 0.11
// Date: Fri Feb 28 09:49:20 2020


`timescale 1ns/10ps

module bin2gray (
    B,
    G
);
// Gray encoder.
// 
// B -- binary input 
// G -- Gray encoded output

input [7:0] B;
output [7:0] G;
wire [7:0] G;





assign G = ((B >>> 1) ^ B);

endmodule
